version: "3"

services:
  api:
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      PORT: 3000
    ports:
      - 3000:3000
    command: npm run dev