version: "3"

services:
  api:
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      PORT: 3000
      MONGO_URL: 'mongodb://user:password@db:27017/xmen?authSource=admin'
    ports:
      - 3000:3000
    command: npm run dev
    networks:
      - mi-compa-net
    depends_on:
      db:
        condition: service_healthy
      
  db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=xmen
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27019:27017
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mi-compa-net

networks:
  mi-compa-net:
    name: mi-compa-net
    driver: bridge