services:
  Shared.Logger:
    class: ../../../../../contexts/shared/infrastructure/WinstonLogger
    arguments: []

  Xmen.Humans.MongoConfig:
    factory:
      class: ../../../../../contexts/xmen/humans/infrastructure/persistence/mongo/MongoConfigFactory
      method: 'createConfig'

  Shared.ConnectionManager:
    factory:
      class: ../../../../../contexts/shared/infrastructure/persistence/mongo/MongoClientFactory
      method: 'createClient'
    arguments: ['xmen', '@Xmen.Humans.MongoConfig']