namespace: ${namespace}

backend:
  image:
    repository: ${backend_image_repository}
    tag: "${backend_image_tag}"


  serviceAccount:
    create: false

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 85
    targetMemoryUtilizationPercentage: 85

  livenessProbe:
    httpGet:
      path: ${backend_healthcheck_path}
      port: http
      scheme: HTTP
    initialDelaySeconds: 15
    periodSeconds: 20

  readinessProbe:
    httpGet:
      path: ${backend_healthcheck_path}
      port: http
      scheme: HTTP
    initialDelaySeconds: 15
    periodSeconds: 20

  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
  
  replicaCount: 1

  env:
    - name: PORT
      value: '${backend_env_port}'
    
    - name: MONGO_URL
      value: '${backend_env_mongo_url}'